// src/data.js

const events = [
  {
    id: 1,
    title: "Tech Conference",
    date: "Thu Jul 13 2023",
    time: "7:00:00 AM IST",
    type: "Offline Event",
    image: "https://images.unsplash.com/photo-1750768145390-f0ad18d3e65b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHwxfHxjb25mZXJlbmNlJTIwcm9vbSUyMGJ1c2luZXNzJTIwbWVldGluZyUyMGxhcHRvcHMlMjBvZmZpY2V8ZW58MHwwfHx8MTc2MDAzNTQ2NXww&ixlib=rb-4.1.0&q=85",
    isPaid: false,
    price: 0,
    venue: "123 Innovation Drive, City",
    hostedBy: "Tech Innovators Inc.",
    description: "A comprehensive conference covering the latest trends in AI, Machine Learning, and Cloud Computing. Join industry leaders for insightful keynotes and workshops.",
    speakers: [
      { name: "Alice Johnson", title: "AI Specialist", image: "https://i.pravatar.cc/150?img=1" },
      { name: "Bob Williams", title: "Cloud Architect", image: "https://i.pravatar.cc/150?img=12" },
    ],
    additionalInfo: {
      dressCode: "Business Casual",
      ageRestrictions: "18 and above",
    },
    tags: ["tech", "conference", "ai", "cloud"],
    sessionTiming: "Thu Jul 13 2023 at 7:00:00 AM to Thu Jul 13 2023 at 5:00:00 PM",
  },
  {
    id: 2,
    title: "Design Workshop",
    date: "Mon Jul 10 2023",
    time: "2:00:00 PM IST",
    type: "Offline Event",
    image: "https://images.unsplash.com/photo-1588561181397-fed38f837e17?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHw0fHxkZXNpZ24lMjBza2V0Y2hlcyUyMG5vdGVib29rJTIwd29ya3NwYWNlJTIwY29mZmVlfGVufDB8MHx8fDE3NjAwMzU0NjV8MA&ixlib=rb-4.1.0&q=85",
    isPaid: true,
    price: 3000,
    venue: "456 Creative Center, City",
    hostedBy: "Design Gurus",
    description: "Learn the fundamentals of modern UI/UX design. This hands-on workshop will cover prototyping, user research, and design thinking principles.",
    speakers: [
      { name: "Cathy Lee", title: "UX Lead", image: "https://i.pravatar.cc/150?img=5" },
    ],
    additionalInfo: {
      dressCode: "Casual",
      ageRestrictions: "None",
    },
    tags: ["design", "workshop", "ui", "ux"],
    sessionTiming: "Mon Jul 10 2023 at 2:00:00 PM to Mon Jul 10 2023 at 5:00:00 PM",
  },
  {
    id: 3,
    title: "Marketing Seminar",
    date: "Tue Aug 15 2023",
    time: "10:00:00 AM IST",
    type: "Offline Event",
    image: "https://images.unsplash.com/photo-1758691736821-f1a600c0c3f1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHwxfHxwcmVzZW50YXRpb24lMjBjaGFydHMlMjBzZW1pbmFyJTIwc3BlYWtlciUyMGF1ZGllbmNlfGVufDB8MHx8fDE3NjAwMzU0NjV8MA&ixlib=rb-4.1.0&q=85",
    isPaid: true,
    price: 3000,
    venue: "Marketing City, 789 Marketing Avenue, City",
    hostedBy: "Marketing Experts",
    description: "Stay ahead of the game in the dynamic field of digital marketing by attending the Marketing Seminar organized by Marketing Experts. This offline seminar will be held on August 15th from 10:00 AM to 12:00 PM at Marketing City, situated at 789 Marketing Avenue, City. Join industry leaders Sarah Johnson, Marketing Manager, and Michael Brown, SEO Specialist, as they delve into the latest trends and strategies in digital marketing. The seminar is open to individuals aged 18 and above and requires a ticket priced at ₹3,000. The dress code for the event is smart casual.",
    speakers: [
      { name: "Sarah Johnson", title: "Marketing Manager", image: "https://i.pravatar.cc/150?img=47" },
      { name: "Michael Brown", title: "SEO Specialist", image: "https://i.pravatar.cc/150?img=13" },
    ],
    additionalInfo: {
      dressCode: "Smart casual",
      ageRestrictions: "18 and above",
    },
    tags: ["marketing", "digital"],
    sessionTiming: "Tue Aug 15 2023 at 10:00:00 AM to Tue Aug 15 2023 at 12:00:00 PM",
  },
  {
    id: 4,
    title: "Financial Freedom Summit",
    date: "Wed Sep 20 2023",
    time: "6:00:00 PM IST",
    type: "Online Event",
    image: "https://images.unsplash.com/photo-1586448681913-2fc1b29c5cca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHwyfHxmaW5hbmNlJTIwY2hhcnRzJTIwaW52ZXN0bWVudCUyMG1vbmV5JTIwYnVzaW5lc3N8ZW58MHwwfHxibHVlfDE3NjAwMzU0NjV8MA&ixlib=rb-4.1.0&q=85",
    isPaid: true,
    price: 1500,
    venue: "Online via Zoom",
    hostedBy: "Wealth Advisors",
    description: "An online summit to help you achieve financial independence. Topics include budgeting, investing, and passive income streams.",
    speakers: [
      { name: "David Chen", title: "Financial Planner", image: "https://i.pravatar.cc/150?img=33" },
    ],
    additionalInfo: {
      dressCode: "N/A",
      ageRestrictions: "None",
    },
    tags: ["finance", "online", "investing"],
    sessionTiming: "Wed Sep 20 2023 at 6:00:00 PM to Wed Sep 20 2023 at 8:00:00 PM",
  },
  {
    id: 5,
    title: "Photography Basics Webinar",
    date: "Fri Oct 6 2023",
    time: "4:00:00 PM IST",
    type: "Online Event",
    image: "https://images.unsplash.com/photo-1758613656356-b3d9030a9ff8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHwxfHxwaG90b2dyYXBoeSUyMGNhbWVyYSUyMHBob3RvZ3JhcGhlcnMlMjBjcmVhdGl2ZXxlbnwwfDB8fHwxNzYwMDM1NDY1fDA&ixlib=rb-4.1.0&q=85",
    isPaid: false,
    price: 0,
    venue: "Online via Google Meet",
    hostedBy: "Creative Minds Collective",
    description: "Master the basics of photography, from camera settings to composition. Perfect for beginners and enthusiasts.",
    speakers: [
      { name: "Emily White", title: "Professional Photographer", image: "https://i.pravatar.cc/150?img=20" },
    ],
    additionalInfo: {
      dressCode: "N/A",
      ageRestrictions: "None",
    },
    tags: ["photography", "online", "art", "creative"],
    sessionTiming: "Fri Oct 6 2023 at 4:00:00 PM to Fri Oct 6 2023 at 5:30:00 PM",
  },
  {
    id: 6,
    title: "Data Science Bootcamp",
    date: "Sat Nov 18 2023",
    time: "9:00:00 AM IST",
    type: "Offline Event",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTAwNDR8MHwxfHNlYXJjaHwxfHxkYXRhJTIwc2NpZW5jZSUyMGFuYWx5dGljcyUyMGNoYXJ0c3xlbnwwfDB8fHwxNzYwMDM1NDY1fDA&ixlib=rb-4.1.0&q=85",
    isPaid: true,
    price: 5000,
    venue: "Tech Hub, 321 Data Street, City",
    hostedBy: "Data Science Academy",
    description: "Dive deep into the world of data science with our intensive bootcamp. Learn Python, machine learning algorithms, data visualization, and statistical analysis. This hands-on bootcamp covers everything from data preprocessing to building predictive models. Perfect for aspiring data scientists and analysts looking to break into the field.",
    speakers: [
      { name: "Dr. Lisa Chen", title: "Data Scientist", image: "https://i.pravatar.cc/150?img=48" },
      { name: "James Wilson", title: "ML Engineer", image: "https://i.pravatar.cc/150?img=14" },
    ],
    additionalInfo: {
      dressCode: "Casual",
      ageRestrictions: "18 and above",
    },
    tags: ["data science", "machine learning", "python", "analytics"],
    sessionTiming: "Sat Nov 18 2023 at 9:00:00 AM IST to Sat Nov 18 2023 at 5:00:00 PM IST",
  },
];

export const getEvents = () => events;
export const getEventById = (id) => events.find(event => event.id === parseInt(id));